version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.11
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea_postgres
      - GITEA__database__PASSWD=2nQnoGmgYPKNx9htwT8b
      - GITEA_CUSTOM=/custom
    restart: always
    networks:
      - gitea
    volumes:
      - ./custom:/custom
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea_postgres
      - POSTGRES_PASSWORD=2nQnoGmgYPKNx9htwT8b
      - POSTGRES_DB=gitea
    networks:
      - gitea
      - proxy-manager_default
    volumes:
      - ./postgres:/var/lib/postgresql/data
